name: WordPresenter CI/CD

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 19.x 20.x, 21.x, 22.x] # Removed outdated Node.js versions and kept stable ones for Angular 19 compatibility.

    timeout-minutes: 03 # Set a timeout of 30 minutes for the build job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci # `npm ci` is faster and ensures a clean installation.

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test -- --watch=false

      - name: Custom step
        run: echo "Custom CI step completed"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    timeout-minutes: 03 # Set a timeout of 30 minutes for the deploy job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git metadata
        id: vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t teclit/wordpresenter:${{ env.BRANCH_NAME }}-${{ env.COMMIT_SHA }} .

      - name: Tag Docker image as latest
        run: docker tag teclit/wordpresenter:${{ env.BRANCH_NAME }}-${{ env.COMMIT_SHA }} teclit/wordpresenter:latest

      - name: Push Docker image to Docker Hub with dynamic tag
        run: docker push teclit/wordpresenter:${{ env.BRANCH_NAME }}-${{ env.COMMIT_SHA }}

      - name: Push Docker image to Docker Hub with latest tag
        run: docker push teclit/wordpresenter:latest
